### ISSUE TITLE
The compute_merged_total_length has something wrong

### ISSUE THREAD

**Issue by yellowishee** [wq2012/SimpleDER#1]
This function doesn't consider the situation like :
ref = [('a', 1.0, 2.0)]
hyp = [('a', 1.0, 1.6), ('a', 1.7, 2.5)]

The output of this function is :
[(1.0, 2.0), (1.7, 2.5)]
1.7999999

But actually the union of ref and hyp is [(1.0, 2.5)] or [(1.0, 2.0), (2.0, 2.5)] and the merged total length is 1.5, right?

**Comment by ciscodario** [comment]
The total length is 1.4 in this case

**Comment by wq2012** [comment]
Thanks! The bug has been fixed.
